### ISSUE TITLE
Add demo to README.md 

### ISSUE THREAD

**Issue by marcospb19** [clercjs/clerc#151]
In order to help your goal of making this project reach 100+ stars, I think you should add demos to the README where people can straight up look at a code sample.

It takes too many clicks (and some scrolling) to get to the "getting started" part where the first snippet is shown.

References:
- [Clap's docs page](https://docs.rs/clap/latest/clap).
- [Clap examples folder with a README (that could also have a small snippet in it).](https://github.com/clap-rs/clap/tree/master/examples)

If you focus on usability (and give a snippet demo), people will definitely see the value in your lib.

EDIT: also, I believe the `examples/` folder in `clap` is all automatically tested, the `.md` files provide the input in the first line, and the expected output in the rest, so you guarantee that your examples always work.

**Comment by so1ve** [comment]
Makes sense, thanks for your suggestion!
